logging:
  level:
    root: INFO
    jasypt: INFO
spring:
  sql:
    init:
      encoding: utf-8

  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        ddl-auto: update

  datasource:
    url: ENC(KZZmF4xUS1kxL20Zs3LlYVRPkFwwAom68AT0n+p/CfZM1WHYELGzXeqcetas4brvPMq5YINYCvJsiR1lQkc7+MujQHBZ9i124uWi61VoqtOjeeHHSq3CiS7jeD7+NgwtFo7+MU2zyGQOAzPNPtswS6Wdfo/2D/p2gawCs5uJ7z5gsI9+jIfM3vuN/MKd5yKy1j+JSMY6J3I=)
    username: ENC(S2yxfx+SmIbLvucKCZFTZv2u9FyffGx6)
    password: ENC(oA6dcHBq/ub/DqGQBY7XPEtLzPL8MSEZx3BZ3DyYE/I=)
    sql-script-encoding: utf-8

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(LeQXynikEt8LFG1osKV6mfyxNbSqPjRxejEBZXPTHd8U94480eRVyqUf7wMZyNmaAziI5Ki+1SSnqgTfA9sVY2DYITZKCKJD8meAkq22BIGQy0fOAQtgy9O6LAXAXoqD)
            client-secret: ENC(qcvq9C3Ppj7ed074/W7sSC076P+615S+THp1kW6FXHTYFRlo1nJXZuk4S8YADfbeFX0n7QiPTZg=)
            scope:
              - email
              - profile

          kakao:
            client_id: ENC(nztV58BOLkiBmHh9RKE3/fm1UFarn+1dbKYxAEjCiN7Y21tWuezKbwqLsQyAs+RwqopLN7QZboM=)
            client-secret: ENC(vVBva0uflAmy6gjMiCzoAgTycj2ncf6PtI0/DpXLFy3e3/cBDwpqTwhLzjPmaMQCixQnzdh+JPI=)
            redirect_uri: http://localhost:8080/login/oauth2/code/kakao
            response_type: code
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            #scope: openid, account_email

          naver:
            client_id : ENC(wE/F0ZgZJXbgCfqrALZY/si6wa6FkKzR5eLPAaF2yX0wAFD5JKiXTw==)
            client-secret: ENC(edoli454w59MYZmpMzDu/ISczmqq//1Edyp//yyy0j0=)
            response_type: code
            redirect_uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

apiKey:
  exhibitionSearch: ENC(KTwFpSskSahpn8JHPHNREkXcwVwoXgFWflefvXhYGWb6jrRWycvFIoyAY3bZB9QTBfVCG0Wqtj2XC7sz760szUM9tJ1rOJvvmKkqAjeAvG9D7NX0RKU/cwx8X67uEy7sRJkRuMlMp/SBfR2E1HRdtQ==)
  exhibitionSearchApi2 : ENC(UW7ZCJyYfcynAAm8AYEjep5v3P6qR3HTtxxUdMSlGNu1nIyQmtM1YG6nV3xtZa323wt/ZB0JUzQ=)

jwt:
  issuer: cr0c0
  secret_key: ENC(vi3kSQ7TM6Tq39ehZmX2zP7AxG2LL0Z3IfYKwzmPNq+0ri5gTErbXslQh73wRCdn)

default:
  profileImg: https://i.ibb.co/LzfM6Mx/member1712982423627.jpg